//
//  WMOrderSuccessRouter.swift
//  Wingman
//
//  Created by Kraisorn Soisakhu on 5/17/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol WMOrderSuccessRouterInput {
    
}

protocol WMOrderSuccessRouterDataSource: AnyObject {
    
}

protocol WMOrderSuccessRouterDataDestination: AnyObject {
    
}

class WMOrderSuccessRouter: WMOrderSuccessRouterInput {
    
    weak var viewController: WMOrderSuccessViewController!
    weak private var dataSource: WMOrderSuccessRouterDataSource!
    weak var dataDestination: WMOrderSuccessRouterDataDestination!
    
    init(viewController: WMOrderSuccessViewController, dataSource: WMOrderSuccessRouterDataSource, dataDestination: WMOrderSuccessRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    func navigateBackToStore() {
        self.viewController.navigationController?.popToRootViewController(animated: true)
    }
    
    // MARK: Communication
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
    }
}
