//
//  WMOrderSuccessConfigurator.swift
//  Wingman
//
//  Created by Kraisorn Soisakhu on 5/17/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension WMOrderSuccessInteractor: WMOrderSuccessViewControllerOutput, WMOrderSuccessRouterDataSource, WMOrderSuccessRouterDataDestination {
}

extension WMOrderSuccessPresenter: WMOrderSuccessInteractorOutput {
}

class WMOrderSuccessConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = WMOrderSuccessConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: WMOrderSuccessViewController) {
        
        let presenter = WMOrderSuccessPresenter()
        presenter.output = viewController
        
        let interactor = WMOrderSuccessInteractor()
        interactor.output = presenter
        
        let router = WMOrderSuccessRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
