//
//  WMOrderSuccessPresenter.swift
//  Wingman
//
//  Created by Kraisorn Soisakhu on 5/17/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol WMOrderSuccessPresenterInput {
    
}

protocol WMOrderSuccessPresenterOutput: AnyObject {
    
}

class WMOrderSuccessPresenter: WMOrderSuccessPresenterInput {
    
    weak var output: WMOrderSuccessPresenterOutput?
    
    // MARK: Presentation logic
    
}
