//
//  WMOrderSuccessViewController.swift
//  Wingman
//
//  Created by Kraisorn Soisakhu on 5/17/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol WMOrderSuccessViewControllerInput {
    
}

protocol WMOrderSuccessViewControllerOutput {
    
}

class WMOrderSuccessViewController: UIViewController, WMOrderSuccessViewControllerInput {
    
    var output: WMOrderSuccessViewControllerOutput?
    var router: WMOrderSuccessRouter?
    
    // MARK: Object lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        WMOrderSuccessConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.navigationItem.hidesBackButton = true
        self.navigationController?.interactivePopGestureRecognizer?.isEnabled = false
    }
    
    // MARK: Actions
    @IBAction func doBackToStore(_ sender: UIButton) {
        self.router?.navigateBackToStore()
    }
    
    // MARK: Requests
    
    
    // MARK: Display logic
    
}

//This should be on configurator but for some reason storyboard doesn't detect ViewController's name if placed there
extension WMOrderSuccessViewController: WMOrderSuccessPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router?.passDataToNextScene(for: segue)
    }
}
