//
//  WMStorePresenter.swift
//  Wingman
//
//  Created by Kraisorn Soisakhu on 5/16/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol WMStorePresenterInput {
    
}

protocol WMStorePresenterOutput: AnyObject {
    func presentGetStore(viewModel: WMStoreScene.GetStore.ViewModel)
}

class WMStorePresenter: WMStorePresenterInput {
    
    weak var output: WMStorePresenterOutput?
    
    // MARK: Presentation logic
    func presentGetStore(response: WMStoreScene.GetStore.Response) {
        switch response.result {
        case .success(let resp):
            let data = resp?.data
            let modelData = StoreData(name: data?.name,
                                  rating: data?.rating,
                                  openingTime: data?.openingTime,
                                  closingTime: data?.closingTime)
            let viewModel = WMStoreScene.GetStore.ViewModel(status: .success(model: .init(data: modelData)))
            self.output?.presentGetStore(viewModel: viewModel)
            
        case .failure(let error):
            let viewModel = WMStoreScene.GetStore.ViewModel(status: .failure(title: error?.title, message: error?.message))
            self.output?.presentGetStore(viewModel: viewModel)
        }
    }
}
