//
//  WMStoreViewController.swift
//  Wingman
//
//  Created by Kraisorn Soisakhu on 5/16/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol WMStoreViewControllerInput {
    
}

protocol WMStoreViewControllerOutput {
    func GetStore(request: WMStoreScene.GetStore.Request)
}

class WMStoreViewController: UIViewController, WMStoreViewControllerInput {
    
    var output: WMStoreViewControllerOutput?
    var router: WMStoreRouter?
    
    // MARK: Object lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        WMStoreConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        self.getStoreData()
    }
    
    // MARK: Requests
    
    func getStoreData() {
        let request = WMStoreScene.GetStore.Request()
        self.output?.GetStore(request: request)
    }
    
    // MARK: Display logic
    func presentGetStore(viewModel: WMStoreScene.GetStore.ViewModel) {
        switch viewModel.status {
        case .success(let model):
            print(model.data?.getDisplayText(model.data?.openingTime))
            print(model.data?.getDisplayText(model.data?.closingTime))
        case .failure(let title, let message):
            print(title, message)
        }
    }
}

//This should be on configurator but for some reason storyboard doesn't detect ViewController's name if placed there
extension WMStoreViewController: WMStorePresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router?.passDataToNextScene(for: segue)
    }
}
