//
//  WMStoreConfigurator.swift
//  Wingman
//
//  Created by Kraisorn Soisakhu on 5/16/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension WMStoreInteractor: WMStoreViewControllerOutput, WMStoreRouterDataSource, WMStoreRouterDataDestination {
}

extension WMStorePresenter: WMStoreInteractorOutput {
}

class WMStoreConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = WMStoreConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: WMStoreViewController) {
        
        let presenter = WMStorePresenter()
        presenter.output = viewController
        
        let interactor = WMStoreInteractor()
        interactor.output = presenter
        
        let router = WMStoreRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
