//
//  WMStoreModels.swift
//  Wingman
//
//  Created by Kraisorn Soisakhu on 5/16/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates
//
//  Type "usecase" for some magic!

import Foundation

struct WMStoreScene {
    
    struct GetStore {
        
        struct Request {
            
        }
        
        struct Response {
            let result: GetStoreResult
        }
        
        struct ViewModel {
            let status: Status
            
            enum Status {
                case success(model: Model)
                case failure(title: String?, message: String?)
            }
            
            struct Model {
                let data: StoreData?
                
                struct StoreData {
                    let name: String?
                    let rating: Double?
                    let openingTime: String?
                    let closingTime: String?
                }
            }
        }
    }
}


typealias StoreData = WMStoreScene.GetStore.ViewModel.Model.StoreData
extension StoreData {
    func getDisplayText(_ timeString: String?) -> String {
        guard let time = timeString else {
            return ""
        }
        //15:01:01.772Z
        return String(time.prefix(5))
    }
}
