//
//  WMStoreInteractor.swift
//  Wingman
//
//  Created by Kraisorn Soisakhu on 5/16/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import Foundation

protocol WMStoreInteractorInput {
    
}

protocol WMStoreInteractorOutput {
    func presentGetStore(response: WMStoreScene.GetStore.Response)
}

protocol WMStoreDataSource {
    
}

protocol WMStoreDataDestination {
    
}

class WMStoreInteractor: WMStoreInteractorInput, WMStoreDataSource, WMStoreDataDestination {
    
    var output: WMStoreInteractorOutput?
    
    // MARK: Business logic
    
    func GetStore(request: WMStoreScene.GetStore.Request) {
        
        WMServiceWorker().getStore { result in
            let response = WMStoreScene.GetStore.Response(result: result)
            self.output?.presentGetStore(response: response)
        }
    }
}
