//
//  WMStoreRouter.swift
//  Wingman
//
//  Created by Kraisorn Soisakhu on 5/16/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol WMStoreRouterInput {
    
}

protocol WMStoreRouterDataSource: AnyObject {
    
}

protocol WMStoreRouterDataDestination: AnyObject {
    
}

class WMStoreRouter: WMStoreRouterInput {
    
    weak var viewController: WMStoreViewController!
    weak private var dataSource: WMStoreRouterDataSource!
    weak var dataDestination: WMStoreRouterDataDestination!
    
    init(viewController: WMStoreViewController, dataSource: WMStoreRouterDataSource, dataDestination: WMStoreRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    
    // MARK: Communication
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
    }
}
