//
//  WMOrderInteractor.swift
//  Wingman
//
//  Created by Kraisorn Soisakhu on 5/17/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol WMOrderInteractorInput {
    
}

protocol WMOrderInteractorOutput {
    func presentConfirmOrder(response: WMOrderScene.ConfirmOrder.Response)
}

protocol WMOrderDataSource {
    
}

protocol WMOrderDataDestination {
    var selectProduct: [Product] { get set }
}

class WMOrderInteractor: WMOrderInteractorInput, WMOrderDataSource, WMOrderDataDestination {
    
    var output: WMOrderInteractorOutput?
    var selectProduct: [Product] = []
    
    // MARK: Business logic
    
    func confirmOrder(request: WMOrderScene.ConfirmOrder.Request) {
        let products = self.selectProduct.compactMap { $0.toDictionary }
        WMServiceWorker().confirmOrder(products, order_address: request.address) { result in
            let response = WMOrderScene.ConfirmOrder.Response(result: result)
            self.output?.presentConfirmOrder(response: response)
        }
    }
}
