//
//  WMOrderConfigurator.swift
//  Wingman
//
//  Created by Kraisorn Soisakhu on 5/17/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension WMOrderInteractor: WMOrderViewControllerOutput, WMOrderRouterDataSource, WMOrderRouterDataDestination {
}

extension WMOrderPresenter: WMOrderInteractorOutput {
    
}

class WMOrderConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = WMOrderConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: WMOrderViewController) {
        
        let presenter = WMOrderPresenter()
        presenter.output = viewController
        
        let interactor = WMOrderInteractor()
        interactor.output = presenter
        
        let router = WMOrderRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
