//
//  WMOrderPresenter.swift
//  Wingman
//
//  Created by Kraisorn Soisakhu on 5/17/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol WMOrderPresenterInput {
    
}

protocol WMOrderPresenterOutput: class {
    
}

class WMOrderPresenter: WMOrderPresenterInput {
    
    weak var output: WMOrderPresenterOutput?
    
    // MARK: Presentation logic
    
}
