//
//  WMOrderModels.swift
//  Wingman
//
//  Created by Kraisorn Soisakhu on 5/17/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates
//
//  Type "usecase" for some magic!

struct WMOrderScene {
    struct ConfirmOrder {
        
        struct Request {
            let address: String
        }
        
        struct Response {
            let result: ConfirmOrderResult
        }
        
        struct ViewModel {
            let status: Status
            
            enum Status {
                case success
                case failure(title: String?, message: String?)
            }
        }
    }
}
