//
//  WMOrderPresenter.swift
//  Wingman
//
//  Created by Kraisorn Soisakhu on 5/17/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol WMOrderPresenterInput {
    
}

protocol WMOrderPresenterOutput: AnyObject {
    func displayConfirmOrder(viewModel: WMOrderScene.ConfirmOrder.ViewModel)
}

class WMOrderPresenter: WMOrderPresenterInput {
    
    weak var output: WMOrderPresenterOutput?
    
    // MARK: Presentation logic
    func presentConfirmOrder(response: WMOrderScene.ConfirmOrder.Response) {
        switch response.result {
        case .success:
            let viewModel = WMOrderScene.ConfirmOrder.ViewModel.init(status: .success)
            self.output?.displayConfirmOrder(viewModel: viewModel)
            
        case .failure(let error):
            let viewModel = WMOrderScene.ConfirmOrder.ViewModel.init(status: .failure(title: error?.title, message: error?.message))
            self.output?.displayConfirmOrder(viewModel: viewModel)
        }
    }
}
