//
//  WMOrderRouter.swift
//  Wingman
//
//  Created by Kraisorn Soisakhu on 5/17/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol WMOrderRouterInput {
    
}

protocol WMOrderRouterDataSource: AnyObject {
    
}

protocol WMOrderRouterDataDestination: AnyObject {
    var selectProduct: [Product] { get set }
}

class WMOrderRouter: WMOrderRouterInput {
    
    weak var viewController: WMOrderViewController!
    weak private var dataSource: WMOrderRouterDataSource!
    weak var dataDestination: WMOrderRouterDataDestination!
    
    init(viewController: WMOrderViewController, dataSource: WMOrderRouterDataSource, dataDestination: WMOrderRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    func navigateToOrderSuccess() {
        guard let vc: WMOrderSuccessViewController = UIStoryboard(name: "OrderSuccess", bundle: nil).instantiateViewController(withIdentifier: "WMOrderSuccessViewController") as? WMOrderSuccessViewController else {
            return
        }
        
        self.viewController.navigationController?.pushViewController(vc, animated: true)
    }
    
    // MARK: Communication
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
    }
}
