//
//  WMOrderViewController.swift
//  Wingman
//
//  Created by Kraisorn Soisakhu on 5/17/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol WMOrderViewControllerInput {
    
}

protocol WMOrderViewControllerOutput {
    func confirmOrder(request: WMOrderScene.ConfirmOrder.Request)
}

class WMOrderViewController: UIViewController, WMOrderViewControllerInput {
    
    var output: WMOrderViewControllerOutput?
    var router: WMOrderRouter?
    
    // MARK: Object lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        WMOrderConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
    }
    
    // MARK: Actions
    @IBAction func doConfirmOrder(_ sender: UIButton) {
        self.requestConfirmOrder()
    }
    
    // MARK: Requests
    func requestConfirmOrder() {
        let request = WMOrderScene.ConfirmOrder.Request(address: "abc")
        self.output?.confirmOrder(request: request)
    }
    
    // MARK: Display logic
    func displayConfirmOrder(viewModel: WMOrderScene.ConfirmOrder.ViewModel) {
        switch viewModel.status {
        case .success:
            self.router?.navigateToOrderSuccess()
            
        case .failure(let title, let message):
            print(title ?? "", message ?? "")
        }
    }
}

//This should be on configurator but for some reason storyboard doesn't detect ViewController's name if placed there
extension WMOrderViewController: WMOrderPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router?.passDataToNextScene(for: segue)
    }
}
